### ISSUE TITLE
Missing script `build-simple-cdd`

### ISSUE THREAD

**Issue by paulmenzel** [Nitrokey/debian-oem#7]
https://github.com/Nitrokey/debian-oem/blob/4ec8411339d95ebb0fc990083e7b53a538c1e0d2/Makefile#L15

The repository does not contain that script.

**Comment by paulmenzel** [comment]
Ah, it’s from the Debian package [*simple-cdd*](https://packages.debian.org/sid/simple-cdd), which is installed in the Docker image.

**Comment by paulmenzel** [comment]
This could be mentioned in the README.

**Comment by daringer** [comment]
Good point, added "needed packages" to the readme.md, thanks
